# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=50)),
                ('username', models.CharField(max_length=50, unique='true')),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
